"""SQLAlchemy 2.0 async model for audit_event — partitioned audit log."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    ARRAY,
    BigInteger,
    DateTime,
    Index,
    PrimaryKeyConstraint,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from agentsys.models.base import ALEMBIC_OWNED, Base


class AuditEvent(Base):
    """Partitioned audit event table.

    Partitioned by RANGE (occurred_at) monthly.
    Columns match REQ-AUDIT-41 from the D-007 spec.

    PostgreSQL requires all PRIMARY KEY and UNIQUE constraints on a
    partitioned table to include all partition key columns.
    Therefore:
    - PRIMARY KEY is (occurred_at, id)
    - UNIQUE is (occurred_at, correlation_id, sequence)
    """

    __tablename__ = "audit_event"

    # id — BIGINT GENERATED ALWAYS AS IDENTITY (composite PK in __table_args__)
    id: Mapped[int] = mapped_column(
        BigInteger,
        autoincrement=True,
    )

    # UUID identifier.
    #
    # NOT declared unique, deliberately. PostgreSQL requires every UNIQUE
    # constraint on a partitioned table to contain the partition key, so a bare
    # UNIQUE(event_id) is DDL it will refuse — and the migration accordingly
    # creates none. Declaring `unique=True` here produced a constraint that
    # exists in the ORM's mental model and nowhere in the database: verified by
    # inserting the same event_id twice against the migrated table, which
    # succeeded.
    #
    # Nothing depends on it today (event_id is generated by uuid.uuid4() in
    # recorder.py and never queried), so the honest fix is to stop claiming it.
    # If idempotency on event_id is ever needed, it has to be
    # UNIQUE(occurred_at, event_id) in a migration, not a flag here.
    event_id: Mapped[uuid.UUID] = mapped_column()

    # Partition key + PK component (composite PK in __table_args__)
    #
    # Base.type_annotation_map now makes DateTime(timezone=True) the default
    # for every Mapped[datetime] in the project, so this is redundant — and
    # kept anyway, on this column only. It is the partition key: a row whose
    # timestamp is off by a UTC offset lands in the wrong monthly partition,
    # and this is the column whose bare annotation (D-043) silently rejected
    # 100% of audit writes while all 634 tests passed. Stating the type where
    # it broke costs one argument and documents the constraint in place.
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Correlation + sequence for ordering
    correlation_id: Mapped[str] = mapped_column(
        nullable=False,
    )
    sequence: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
    )

    # Event taxonomy
    event_type: Mapped[str] = mapped_column(
        nullable=False,
    )

    # Agent identity
    role: Mapped[str | None] = mapped_column(nullable=True)
    deployment: Mapped[str | None] = mapped_column(nullable=True)
    actor: Mapped[str | None] = mapped_column(nullable=True)
    tool_name: Mapped[str | None] = mapped_column(nullable=True)

    # Policy decision
    policy_decision: Mapped[str | None] = mapped_column(nullable=True)
    policy_reason: Mapped[str | None] = mapped_column(nullable=True)

    # Payload — JSONB.
    #
    # Must be the postgresql JSONB type, not generic JSON. The migration
    # creates JSONB, and the mismatch was invisible because pg_cast carries an
    # assignment cast json->jsonb, so INSERTs kept working. It cost two things
    # anyway: the GIN index below is DDL PostgreSQL refuses on a json column
    # ("data type json has no default operator class"), making this table
    # un-creatable from metadata and leaving the ALEMBIC_OWNED guard as the
    # only reason nobody noticed; and `payload.contains(...)` would compile
    # with json semantics, unable to use ix_audit_event_payload_gin.
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )

    # PII keys — TEXT[] (Postgres array of text)
    pii_keys: Mapped[list[str] | None] = mapped_column(
        ARRAY(String),
        nullable=True,
    )

    __table_args__ = (
        # Composite PRIMARY KEY — (occurred_at, id)
        PrimaryKeyConstraint("occurred_at", "id", name="pk_audit_event"),
        # Composite UNIQUE — (occurred_at, correlation_id, sequence)
        UniqueConstraint(
            "occurred_at",
            "correlation_id",
            "sequence",
            name="uq_audit_event_correlation_sequence",
        ),
        # BTree index: role + occurred_at DESC (most selective first)
        Index("ix_audit_event_role_occurred", "role", occurred_at.desc()),
        # BTree index: tool_name + occurred_at DESC — partial
        Index("ix_audit_event_tool_occurred", "tool_name", occurred_at.desc()),
        # GIN index on payload for containment queries
        Index(
            "ix_audit_event_payload_gin",
            "payload",
            postgresql_using="gin",
        ),
        # Alembic owns this table's DDL, and the ORM must never create it.
        # The RANGE partitioning above has no SQLAlchemy construct, so
        # `Base.metadata.create_all` would emit a plain unpartitioned table on
        # PostgreSQL (silently) and fail on SQLite (on the composite PK).
        # `alembic_owned_tables` reads this flag; see models/base.py.
        {"info": {ALEMBIC_OWNED: True}},
    )


def map_to_audit_event(event_data: dict[str, Any]) -> AuditEvent:
    """Convert a Pydantic AuditEvent sub-model instance (as dict) to an AuditEvent ORM row.

    This mapper lives here (PR-1) so that PR-2's Pydantic models can depend on it.
    The Pydantic discriminated union events are NOT yet defined — this accepts
    a dict that matches the shape of the eventual AuditEvent Pydantic sub-model.

    Args:
        event_data: Dict with at minimum event_id, occurred_at, correlation_id,
            sequence, event_type, payload. Optional: role, deployment, actor,
            tool_name, policy_decision, policy_reason, pii_keys.

    Returns:
        An unsaved AuditEvent ORM instance.
    """
    return AuditEvent(
        event_id=event_data["event_id"],
        occurred_at=event_data.get("occurred_at", datetime.now(timezone.utc)),
        correlation_id=event_data["correlation_id"],
        sequence=event_data["sequence"],
        event_type=event_data["event_type"],
        role=event_data.get("role"),
        deployment=event_data.get("deployment"),
        actor=event_data.get("actor"),
        tool_name=event_data.get("tool_name"),
        policy_decision=event_data.get("policy_decision"),
        policy_reason=event_data.get("policy_reason"),
        payload=event_data["payload"],
        pii_keys=event_data.get("pii_keys"),
    )
